version: 2
updates:

  # Maintain dependencies for pnpm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "tsdevau"
    reviewers:
      - "tsdevau"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "tsdevau"
    reviewers:
      - "tsdevau"
